---  # tasks file for rkhunter

- name: Install rkhunter
  apt:
    name: rkhunter
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
    state: present
  tags:
    - rkhunter
    - rkhunter-install

- name: Configure /etc/rkhunter.conf
  template:
    src: "etc/rkhunter.conf.j2"
    dest: /etc/rkhunter.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - rkhunter
    - rkhunter-configuration

- name: Configure /etc/default/rkhunter
  template:
    src: etc/default/rkhunter.j2
    dest: /etc/default/rkhunter
    owner: root
    group: root
    mode: 0644
  tags:
    - rkhunter
    - rkhunter-configuration

- name: rkhunter update
  command: rkhunter --update
  register: rkhunter_update
  failed_when: rkhunter_update.rc != 2 and rkhunter_update.rc != 0
  changed_when: false
  tags:
    - rkhunter
    - rkhunter-update

- name: Copy .dat from ansible host to local machine
  ansible.builtin.copy:
    src: /tmp/rkhunter/rkhunter.dat-{{ inventory_hostname }}
    dest: /var/lib/rkhunter/db/rkhunter.dat

- name: Copy script files
  copy:
    src: '{{item}}'
    dest: '/usr/share/rkhunter'
    mode: 077
  loop:
    - rkhunter_log_scanner.py
    - rkhunter_log_scanner.sh


- name: Ensure a scanner that runs every 30 minutes
  ansible.builtin.cron:
    name: "run rkhunter"
    minute: "0,30"
    job: "/usr/share/rkhunter_log_scanner.sh"
  tags:
    - rkhunter
    - rkhunter-cronjob
  # tags: [ never, debug ]
